name: sweap 
description: spiral arms
program: train.py
method: bayes
metric:
  name: epoch/IoU_1
  goal: maximize
parameters:
  loss_gamma:
    distribution: uniform
    max: 3.0
    min: 1.0
  loss_alpha:
    distribution: uniform
    max: 0.37
    min: 0.0
  loss_smoothing:
    distribution: uniform
    max: 1.0
    min: 0.0
  learning_rate: 
    distribution: uniform
    max: 0.01
    min: 0.001
  batch_normalization: 
    values: [
      False,
      True,
    ]
  kernel_regularizer:
    values: [
      None,
      l1,
      l2,
      l1_l2
    ]
  activation:
    values: ['ReLU', 'Softmax']
  output_activation:
    values: ['ReLU', 'Softmax', 'Sigmoid', None]
  atten_activation:
    values: ['ReLU', 'Softmax', 'Sigmoid', None]
  attention:
    values: ["add", "multiply"]
  unpool:
    values: [True, False, 'bilinear', 'nearest']
  pool:
    values: [True, False, 'max', 'ave']
  stack_num_down:
    values: [2, 3, 5, 7]
  stack_num_up:
    values: [2, 3, 5, 7]
