---
fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        args: [--skip-string-normalization]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [--settings-path=pyproject.toml, --line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    - id: flake8
      name: flake8
      exclude: (docs|tsa/alembic/)
      args: [--max-line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
    - id: mypy
      name: mypy
      args: [--ignore-missing-imports, --follow-imports=skip, --show-error-codes]
      additional_dependencies: ['types-requests']

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
      name: bandit
      exclude: (tests|tsa/alembic/)

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
