version: '3'
services:

  # ETL
  imgalaxy:
    build: .
    image: imgalaxy:latest
    container_name: imgalaxy
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    expose:
      - ${JUPYTER_PORT}
    volumes:
      - ${GALAXY_ZOO_DIR}:/root/tensorflow_datasets/galaxy_zoo3d
      - type: bind
        source: ./imgalaxy
        target: /imgalaxy/imgalaxy
    working_dir: /imgalaxy/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TF_GPU_ALLOCATOR=cuda_malloc_async
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - WANDB_API_KEY=${WANDB_API_KEY}

    networks:
      - imgalaxy-network

# NETWORKS
networks:
  imgalaxy-network:
    driver: bridge
