version: '3'
services:

  # ETL
  imgalaxy:
    build: .
    container_name: imgalaxy
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    expose:
      - ${JUPYTER_PORT}
    command: bash -c "tail -f /dev/null"
    volumes:
      - ${GALAXY_ZOO_DIR}:/tensorflow_datasets/downloadas/manual/dataset
      - type: bind
        source: ./imgalaxy
        target: /imgalaxy/imgalaxy
      - type: bind
        source: ./.env
        target: /imgalaxy/.env
    working_dir: /imgalaxy/

    networks:
      - imgalaxy-network

# NETWORKS
networks:
  imgalaxy-network:
    driver: bridge
